name: qortal-ui
version: 1.6.3
summary: Qortal UI for Linux
description: Qortal Project - decentralize the world - Data storage, communications, web hosting, decentralized trading, complete infrastructure for the future blockchain-based Internet.
confinement: strict
grade: stable
icon: snap/gui/256x256.png
architectures:
  - build-on: amd64
    run-on: [amd64, armhf, arm64, i386, ppc64el, s390x]
base: core18
apps:
  qortal-ui:
    command: qortal-ui
    plugs:
      - desktop
      - desktop-legacy
      - home
      - x11
      - unity7
      - browser-support
      - network
      - gsettings
      - pulseaudio
      - opengl
parts:
  app:
    plugin: dump
    stage-packages:
      - libasound2
      - libgconf2-4
      - libnotify4
      - libnspr4
      - libnss3
      - libpcre3
      - libpulse0
      - libxss1
      - libxtst6
    source: dist/linux-unpacked
    after:
      - desktop-gtk3
